"""Configuration-related CLI commands."""

from __future__ import annotations

import typer

from .core import app, console

config_app = typer.Typer(help="Manage yeoman configuration")
app.add_typer(config_app, name="config")


@config_app.command("migrate-to-env")
def config_migrate_to_env(
    force: bool = typer.Option(False, "--force", help="Overwrite existing .env file"),
) -> None:
    """Migrate API keys and tokens from config.json to .env file."""
    from yeoman.config.loader import get_config_path, load_config, save_config
    from yeoman.providers.registry import PROVIDERS
    from yeoman.utils.helpers import get_data_path

    env_path = get_data_path() / ".env"
    if env_path.exists() and not force:
        console.print(f"[yellow].env already exists at {env_path}[/yellow]")
        console.print("Use --force to overwrite it.")
        raise typer.Exit(1)

    config = load_config()

    lines: list[str] = [
        "# yeoman secrets — generated by: yeoman config migrate-to-env",
        "# DO NOT COMMIT this file.",
        "",
        "# LLM Provider API Keys",
    ]
    migrated: list[str] = []

    for spec in PROVIDERS:
        provider = getattr(config.providers, spec.name, None)
        if provider is None:
            continue
        key = (provider.api_key or "").strip()
        if key:
            lines.append(f"{spec.env_key}={key}")
            migrated.append(spec.env_key)
            provider.api_key = ""

    el = config.providers.elevenlabs
    el_key = (el.api_key or "").strip()
    if el_key:
        lines.append(f"ELEVENLABS_API_KEY={el_key}")
        migrated.append("ELEVENLABS_API_KEY")
        el.api_key = ""

    lines += ["", "# Channel Tokens"]

    tg_token = (config.channels.telegram.token or "").strip()
    if tg_token:
        lines.append(f"TELEGRAM_BOT_TOKEN={tg_token}")
        migrated.append("TELEGRAM_BOT_TOKEN")
        config.channels.telegram.token = ""

    wa_token = (config.channels.whatsapp.bridge_token or "").strip()
    if wa_token:
        lines.append(f"WHATSAPP_BRIDGE_TOKEN={wa_token}")
        migrated.append("WHATSAPP_BRIDGE_TOKEN")
        config.channels.whatsapp.bridge_token = ""

    lines += ["", "# Tool API Keys"]

    search_key = (config.tools.web.search.tavily_api_key or "").strip()
    if search_key:
        lines.append(f"TAVILY_API_KEY={search_key}")
        migrated.append("TAVILY_API_KEY")
        config.tools.web.search.tavily_api_key = ""

    if not migrated:
        console.print("[yellow]No non-empty secrets found in config.json to migrate.[/yellow]")
        return

    env_content = "\n".join(lines) + "\n"
    env_path.write_text(env_content, encoding="utf-8")
    try:
        env_path.chmod(0o600)
    except OSError:
        pass

    save_config(config)

    console.print(f"[green]✓[/green] Created {env_path}")
    console.print(f"[green]✓[/green] Migrated {len(migrated)} secret(s): {', '.join(migrated)}")
    console.print(f"[green]✓[/green] Zeroed out secrets in {get_config_path()}")
    console.print("\n[dim]Add .env to your .gitignore. It is already excluded by the default .gitignore.[/dim]")
